name: MLOps CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint:
    name: Lint Code
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      - name: Install Python and Dependencies
        uses: actions/setup-python@v4
        with:
          python-version: '3.8'
      - name: Install Linting Tools
        run: |
          pip install flake8
      - name: Run Linter
        run: flake8 .

  test:
    name: Run Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      - name: Install Python and Dependencies
        uses: actions/setup-python@v4
        with:
          python-version: '3.8'
      - name: Install Testing Tools
        run: |
          pip install pytest
      - name: Run Pytest
        run: pytest

  deploy:
    name: Deploy Model
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      - name: Run Deployment Script
        run: |
          python deploy_model.py
